# Generated by Django 4.0.3 on 2024-04-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=50)),
                ('cobertura', models.CharField(max_length=100)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
